### ISSUE TITLE
Update for Julia 0.7/1.0?

### ISSUE THREAD

**Issue by pbouffard** [NHDaly/PaddleBattleJL#2]
Do you have any plans to update the codebase for 0.7? I so I'd be interested in helping.

**Comment by NHDaly** [comment]
Hi Patrick, that would be amazing!

To be honest, i haven't thought about it, but it shouldn't be too hard I think! :) I would love your help! How should we proceed? 

I just enabled FemtoCleaner for this repo, which feels like a good start!

**Comment by pbouffard** [comment]
Hey, just watched your JuliaCon talk, nice work! Maybe running through the notebook using 0.7 and fixing deprecations and errors would be a good technique, followed by switching to 1.0. Probably most of the work will be discovering which dependencies need attention of course!

So I guess maybe starting a branch in your slides repo for this would be step 1.

**Comment by NHDaly** [comment]
Hey! :) 

This is fixed, finally, in https://github.com/NHDaly/PaddleBattleJL/pull/4.
